<a href="https://colab.research.google.com/github/alazyartist/python_playground/blob/master/Pytorch_Playing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


### making scalars and vectors

In [12]:
scalar = torch.tensor([4])
scalar.ndim

1

In [13]:
scalar.shape

torch.Size([1])

In [16]:
vector1 = torch.tensor([4,2])
vector1.shape

torch.Size([2])

In [22]:
vector = torch.tensor([[4,3,2],[2,3,4]])
vector.ndim

2

In [23]:
vector.shape

torch.Size([2, 3])

In [41]:
randomTensor = torch.rand(3,224,224)
randomTensor.shape, randomTensor.ndim

(torch.Size([3, 224, 224]), 3)

In [46]:
zeroes = torch.zeros(4,2)
ones = torch.ones(4,2)
zeroes,ones

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]), tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]))

In [53]:
rng = torch.arange(1,11)
rng

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### DataTypes

In [56]:
fl32 = torch.tensor([2.1,2.2,2.4])
fl32.dtype

torch.float32

In [58]:
fl16= torch.tensor([2.1,2.2,2.4], dtype=torch.float16)
fl16.dtype

torch.float16

In [61]:
fl16 =fl16.type(torch.float32)
fl16.dtype

torch.float32

In [62]:
mult = torch.matmul(fl16,fl32)
mult

tensor(15.0084)

### Maths

In [70]:
ten1= torch.tensor([4,3,2])
ten2= torch.tensor([1,1,1])
ten1 + ten2

tensor([5, 4, 3])

In [79]:
ten1 @ ten2

tensor(9)

In [77]:
%%time
mult = torch.matmul(ten1,ten2)
mult

CPU times: user 0 ns, sys: 456 µs, total: 456 µs
Wall time: 341 µs


tensor(9)

In [78]:
%%time
value = 0
for i in range (len(ten1)):
  value += ten1[i] * ten2[i]
  print(value)

tensor(4)
tensor(7)
tensor(9)
CPU times: user 3.29 ms, sys: 20 µs, total: 3.31 ms
Wall time: 2.5 ms


when multiplying tensors inner shapes must match

In [87]:
tena = torch.rand(3,4)
tenb =  torch.rand(4,10)
inmatch = torch.matmul(tena,tenb)
tena.shape,tenb.shape,inmatch.shape

(torch.Size([3, 4]), torch.Size([4, 10]), torch.Size([3, 10]))

Swap around shapes with transpose (tensor).T

In [90]:
tena.shape, tena.T.shape 

(torch.Size([3, 4]), torch.Size([4, 3]))

In [91]:
tenb.shape,tenb.T.shape

(torch.Size([4, 10]), torch.Size([10, 4]))